quick:
	./test 1 7 d 500 ll 0 0 2
	./test 1 7 d 500 ll 1 0 2
	./test 1 7 d 500 ll 0 1 2
	./test 1 7 d 500 ll 1 1 2

quick-grad:
	./test 1 7 d 2000 qb 0 0 2
	./test 1 7 d 2000 qb 1 0 2

quick-matlab:
	matlab -nodesktop -nosplash -r "demo;exit"

long:
	./test 1 9 d 500 ll 0 0 2
	./test 1 9 d 500 ll 1 0 2

long-grad:
	./test 1 9 d 2000 qb 0 0 2
	./test 1 9 d 2000 qb 1 0 2

